version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout   
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install --no-cache-dir -r clientes/requirements.txt
      # Step 3: pytest
      - run:
          name: run test
          command: |
            . venv/bin/activate
            pytest
      # Step 4: behave test
      - run:
          name: behave test
          command: |
            . venv/bin/activate
            behave